services:
  - type: web
    name: atypikhouse
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_AUTO_IMPORT
        value: "false"
      - key: DB_AUTO_IMPORT_FORCE
        value: "false"
      - key: DB_ALLOW_PRODUCTION_FORCE_IMPORT
        value: "false"
      - key: BREVO_ENABLED
        value: "false"
